version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "/Users/klook/docker/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=hongyuqin
    networks:
      - mysql_network
  redis:
    image: redis
    ports:
      - 6379:6379
    command:
      redis-server
    networks:
      - mysql_network
networks:
  mysql_network:
    external:
      name: mysql_network